export const Colors = {
  primary: '#007AFF',
  primaryLight: '#E3F2FD',
  background: '#F5F5F7',
  white: '#FFFFFF',
  black: '#000000',
  text: '#1D1D1F',
  textSecondary: '#86868B',
  success: '#34C759',
  warning: '#FF9500',
  danger: '#FF3B30',
  gray: '#8E8E93',
  grayLight: '#F2F2F7',
  border: '#E5E5EA',
  cardBackground: '#FFFFFF',
  shadow: 'rgba(0, 0, 0, 0.1)',
  // Warm light colors for AddAssetScreen
  warmBackground: '#F8F4ED',
  warmCardBackground: '#FFFFFF',
  warmInputBackground: '#EEEAE2',
  warmPrimary: '#5D9B8E',
  warmText: '#3A3A3A',
  warmTextSecondary: '#8B7D6B',
  warmBorder: '#E0D9C8',
  // Orange accent colors for Assets screen
  orange: '#FF6B35',
  orangeLight: '#FFE5DD',
  orangeDark: '#E55A2B',
};
